services:

  # Serviço da API Spring Boot
  api-usuarios:
    build:
      context: .                # Diretório onde está o Dockerfile
      dockerfile: Dockerfile   # Nome do seu Dockerfile
    container_name: apiusuarios_app
    restart: always
    ports:
      - "8082:8082"            # Porta externa 8081 → interna 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/bdapiusuarios
      SPRING_DATASOURCE_USERNAME: apiusuarios
      SPRING_DATASOURCE_PASSWORD: coti2026
    depends_on:
      - postgresql
    networks:
      - apiusuarios-network

  # Banco de dados PostgreSQL
  postgresql:
    image: postgres:16
    container_name: postgresql_apiusuarios
    restart: always
    environment:
      POSTGRES_USER: apiusuarios
      POSTGRES_PASSWORD: coti2026
      POSTGRES_DB: bdapiusuarios
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - apiusuarios-network

  # Interface web do PostgreSQL (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_apiusuarios
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgresql
    networks:
      - apiusuarios-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  apiusuarios-network:
    driver: bridge